server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.wasm$ {
        default_type application/wasm;
        try_files $uri =404;
    }

    location ~* \.data$ {
        default_type application/octet-stream;
        try_files $uri =404;
    }

    location ~* \.js$ {
        default_type application/javascript;
        try_files $uri =404;
    }
}
