syntax = "proto3";

package packets;

option go_package = "./proto";

enum RoomStatus {
  ROOM_STATUS_WAITING = 0;
  ROOM_STATUS_STARTED = 1;
}

enum MatchPhase {
  MATCH_PHASE_PREPARE = 0;
  MATCH_PHASE_ACTIVE = 1;
  MATCH_PHASE_ENDED = 2;
}

message ChatMessage {
  string msg = 1;
}

message IdMessage {
  uint64 id = 1;
}

message StartGameRequestMessage {

}

message LoginRequestMessage {
  string username = 1;
  string password = 2;
}

message RegisterRequestMessage {
  string username = 1;
  string password = 2;
}

message CreateRoomRequestMessage {
  uint32 maxPlayer = 1;
  string roomName = 2;
}

message JoinRoomRequestMessage {
  uint64 roomId = 1;
}

message RoomListRequestMessage {

}

message RoomSummaryMessage {
  string name = 1;
  uint64 roomId = 2;
  repeated RoomPlayerMessage Players = 3;
  uint32 maxPlayer = 4;
  RoomStatus status = 5;
}

message RoomListSnapshotMessage {
  repeated RoomSummaryMessage rooms = 1;
}

message LeaveRoomRequestMessage {

}

message ReadyRequestMessage {
  bool isReady = 1;
}

message RoomPlayerMessage {
  uint64 userId = 1;
  uint64 clientId = 2;
  string username = 3;
  bool isReady = 4;
  bool owner = 5;
}

message JoinRoomResponseMessage {
  RoomPlayerMessage player = 1;
}

message PlayerKickRoom {
  uint64 userId = 1;
}

message PlayerRemoveRoom {
  RoomPlayerMessage player = 1;
}

message PlayersInRoomRequest {
  uint64 roomId = 1;
}

message PlayersInRoomResponse {
  repeated RoomPlayerMessage Player = 1;
}

message RoomStateSnapshotMessage {
  uint64 roomId = 1;
  uint32 maxPlayer = 2;
  RoomStatus status = 3;
  repeated RoomPlayerMessage Player = 4;
}

message MatchStartMessage {
  uint64 roomId = 1;
  uint64 matchId = 2;
  uint64 player_id = 3;
  uint32 slot = 4;
  uint64 mapSeed = 5;
  int64 startsAtUnixMs = 6;
}

message Vector2Message {
  float x = 1;
  float y = 2;
}

message PlayerInputMessage {
  uint64 matchId = 1;
  Vector2Message movePosition = 2;
}

message PlayerCellEntityMessage {
  uint64 id = 1;
  uint64 ownerId = 2;
  Vector2Message position = 3;
  uint32 hp = 4;
  uint32 biomass = 5;
  uint32 level = 6;
  bool alive = 7;
}

message CoreEntityMessage {
  uint64 id = 1;
  uint64 ownerId = 2;
  Vector2Message position = 3;
  uint32 hp = 4;
}

message NutrientEntityMessage {
  uint64 id = 1;
  Vector2Message position = 2;
  uint32 value = 3;
  bool active = 4;
}

message WallEntityMessage {
  uint64 id = 1;
  bool open = 2;
}

message MatchSnapshotMessage {
  uint64 matchId = 1;
  uint64 serverTick = 2;
  MatchPhase phase = 3;
  int64 phaseTimeLeftMs = 4;

  repeated PlayerCellEntityMessage playerCells = 5;
  repeated CoreEntityMessage cores = 6;
  repeated NutrientEntityMessage nutrients = 7;
  repeated WallEntityMessage walls = 8;
}

message OkResponseMessage {

}

message DenyResponseMessage {
  string reason = 1;
}

message Packet {
  uint64 sender_id = 1;
  oneof msg {
    ChatMessage chat = 2;
    IdMessage id = 3;
    LoginRequestMessage login_request = 4;
    RegisterRequestMessage register_request = 5;
    OkResponseMessage ok_response = 6;
    DenyResponseMessage deny_response = 7;
    CreateRoomRequestMessage create_room_request = 8;
    JoinRoomRequestMessage join_room_request = 9;
    LeaveRoomRequestMessage leave_room_request = 10;
    ReadyRequestMessage ready_request = 11;
    RoomStateSnapshotMessage room_state_snapshot = 12;
    MatchStartMessage match_started = 13;
    StartGameRequestMessage start_game = 14;
    RoomSummaryMessage room_summary_message = 15;
    RoomListSnapshotMessage room_list_snapshot = 16;
    PlayerInputMessage player_input = 17;
    MatchSnapshotMessage match_snapshot = 18;
    PlayerKickRoom player_kick_room = 19;
    PlayerRemoveRoom player_remove_room = 20;
    JoinRoomResponseMessage join_room_response_message = 21;
    PlayersInRoomRequest players_in_room_request = 22;
    PlayersInRoomResponse players_in_room_response = 23;
    RoomListRequestMessage room_list_request_message = 24;
  }
}